# This is for exposing the https://alephium.hongchao.me website.
# Requires [cert-manager](https://cert-manager.io/docs/) to be installed
# in your k8s cluster
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alephium-hongchao-me-ingress
  namespace: alephium
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - alephium.hongchao.me
    secretName: alephium-hongchao-me-it-tls
  rules:
  - host: alephium.hongchao.me
    http:
      paths:
      - path: /docs
        pathType: Prefix
        backend:
          service:
            name: alephium
            port:
              number: 12973
      - path: /blocks
        pathType: Prefix
        backend:
          service:
            name: alephium-explorer
            port:
              number: 9090
      - path: /transactions
        pathType: Prefix
        backend:
          service:
            name: alephium-explorer
            port:
              number: 9090
      - path: /addresses
        pathType: Prefix
        backend:
          service:
            name: alephium-explorer
            port:
              number: 9090
      - path: /
        pathType: Prefix
        backend:
          service:
            name: alephium-explorer
            port:
              number: 3000
