apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: balanced-retain
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
parameters:
  type: pd-balanced
  fsType: ext4
allowVolumeExpansion: true