apiVersion: apps/v1
kind: Deployment
metadata:
  name: bridge-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bridge-ui
  template:
    metadata:
      labels:
        app: bridge-ui
      name: bridge-ui
    spec:
      containers:
        - name: bridge-ui
          image: liuhongchao/bridge-ui:0.2.1
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: bridge-ui
spec:
  selector:
    app: bridge-ui
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
