---
apiVersion: v1
kind: Service
metadata:
  name: explorer
  labels:
    app: explorer
spec:
  selector:
    app: explorer
  ports:
    - port: 8001
      name: http
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: explorer
spec:
  selector:
    matchLabels:
      app: explorer
  serviceName: explorer
  replicas: 1
  template:
    metadata:
      labels:
        app: explorer
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: explorer
          image: liuhongchao/wormhole-explorer:0.2.2
          command:
            - /usr/local/bin/npm
            - run
            - serve
          tty: true
          ports:
            - containerPort: 8001
              name: gatsbyserver
              protocol: TCP
          readinessProbe:
            httpGet:
              port: gatsbyserver
              path: /
