# This is for exposing the https://alephium.softfork.se website.
# Requires [cert-manager](https://cert-manager.io/docs/) to be installed
# in your k8s cluster
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alephium-dev-softfork-se-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - alephium-dev.softfork.se
    secretName: alephium-dev-softfork-se-it-tls
  rules:
  - host: alephium-dev.softfork.se
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: alephium
            port:
              number: 22973
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alephium-nft-softfork-se-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - alephium-nft.softfork.se
    secretName: alephium-nft-softfork-se-it-tls
  rules:
  - host: alephium-nft.softfork.se
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: alephium-nft
            port:
              number: 3000
